### ISSUE TITLE
woocomerce action scheduler not working 

### ISSUE THREAD

**Issue by ahsanelahi231** [Prospress/action-scheduler#899] opened 2023-01-10 09:14 UTC
i am facing issue with woocomerce action scheduler my site have this error after ddos attack 
i tried everything to make it work but it doesnt help so i placed the version of my site at which my site is working perfectly fine 
and checked everything working fine but after 2 days same thing happend and i am back to square zero

my issue is my automatic functions are  not working automatically like when someone place the order it wont update the net sales amount i have to run those functions automatically by going at woocomerce and then clicking status and then click run which is not good totally so i need some expert help because i am out of ideas right now..

before ddos attack i am just using wp-rocket and now after ddos attack i am also using cloudfare on my site ...
i have also applied page rules so that it wont cache anything but still it work but after back 2 days still past due actions

**Comment by barryhughes** [comment] 2023-01-11 01:34
Hi @ahsanelahi231,

Sorry to hear you are facing difficulties.

- It's worth checking if the problem is only with Action Scheduler, or if WP Cron has also stopped working. A good guide for this [can be found here](https://woocommerce.com/document/subscriptions/develop/complete-guide-to-scheduled-events-with-subscriptions/) (though written for users of WooCommerce Subscriptions, the general principles are transferrable). In short, if both have stopped working then it is likely that something—be that CloudFlare or the way your hosting environment is set up—is blocking things.
- Can you run scheduled actions manually, via the **Tools → Scheduled Actions** admin screen? If so, that again suggests the problem may be with your hosting environment, or with an addon service like CloudFlare, and not directly with Action Scheduler.
- Do you have access to the command line, and to the [WP CLI](https://wp-cli.org/) tool? If you do, you could consider setting up a crontab rule (or equivalent) that [invokes Action Scheduler's queue runner](https://actionscheduler.org/wp-cli/) this way: `wp action-scheduler run`. You may wish to speak to your host for advice on how to do this in your particular environment.

I hope that helps!

**Closed as completed** 2023-01-25 19:28 UTC
Labels: type: support request
