### ISSUE TITLE
WP-CLI: How do I run two batches concurrently when groups cannot be excluded?

### ISSUE THREAD

**Issue by jonathanjgl** [Prospress/action-scheduler#889] opened 2022-11-18 13:51 UTC
Let's say I want to run a batch based on one group. This could be done with `wp action-scheduler run --group=<group name>`. I also want every other actions to run so I'm using `wp action-scheduler run`. If a group of actions does not depend at all on any other actions, then it would be nice to run two batches concurrently, one batch that excludes a group actions and the other with the group actions. Is this possible, or are there any plans to make this possible?

When I allow two or more batches to run concurrently, the risk is also that `wp action-scheduler run` runs concurrently instead of the wanted combination of `wp action-scheduler run` and  `wp action-scheduler run --group=<group name>` if `wp action-scheduler run` is run more often. Can this be prevented somehow?

**Comment by Konamiman** [comment] 2022-11-22 11:45
Hi @jonathanjgl, thanks for your input.

Unfortunately Action Scheduler doesn't have support for excluding groups when running, and we don't have currently plans to add this feature. That said, there's a workaround that you could use if you are willing to write some code. Since Action Scheduler uses the standard WordPress `$wpdb` object to perform sql queries, you could try to detect the query that selects the actions to run (here's the relevant code: https://github.com/woocommerce/action-scheduler/blob/trunk/classes/data-stores/ActionScheduler_DBStore.php#L372) and change the selecting condition (in this case from `g.slug=%s` to `g.slug=%s`) when you use some special value for the group name (like e.g. `not_<group name>`).

**Comment by peterfabian** [comment] 2022-11-24 13:41
I just wanted to mention I came across a PR yesterday https://github.com/woocommerce/action-scheduler/pull/784 which actually adds the support for including and excluding groups, so it might be coming to AS in not so distant future. 

This means that this issue is probably duplicate of https://github.com/woocommerce/action-scheduler/issues/736, so I'm going to close it now. Please let us know if you disagree @jonathanjgl ! Thanks!

**Closed as completed** 2022-11-24 13:43 UTC
Labels: type: question
