### ISSUE TITLE
Handle malformed date_time in as_get_datetime_object()

### ISSUE THREAD

**Issue by headwalluk** [Prospress/action-scheduler#932] opened 2023-03-19 07:41 UTC
We're seeing a $date_time of " seconds ago" come through into as_get_datetime_object(), which causes the function (and wp-cron) to bawk with a parsing error.

Can we catch this with something like this please?

`
if (is_string($date_string) && (trim($date_string) === 'seconds ago')) {
	$date_string = '0 seconds ago';
}
`

**Comment by barryhughes** [comment] 2023-03-21 16:34
Thanks for flagging this, @headwalluk.

Is there any more information you can provide such as a debug backtrace, that would help us understand the origin of the problem?

> Can we catch this with something like this please?
>
> `if (is_string($date_string) && (trim($date_string) === 'seconds ago')) { $date_string = '0 seconds ago'; }`

Possibly—but I'm not sure it will always make sense to 'cast' to zero seconds. Depending on the circumstances, this might have an adverse effect. So, if we could understand some of the root causes (might this be the result of custom filter functions running on `action_scheduler_timeout_period` or similar?) that would be helpful in figuring out the best solution.

**Comment by headwalluk** [comment] 2023-03-21 18:02
@barryhughes  I host WordPress sites and the error started showing up in the WP CLI cron jobs recently. The instance of the action scheduler is located in the "seo-by-rank-math" plugin. The main WooCommerce plugin is not installed on the site. So, presumably, it's a problem in the Rank Math SEO plugin. I'll take out my modification, let the cron jobs fall over again and come back to you with more info.

**Comment by headwalluk** [comment] 2023-03-21 18:15
There's not much useful in here. Just confirmation that the string is " seconds ago" (with a leading space):

`PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string ( seconds ago) at position 0 (s): The timezone could not be found in the database in /var/www/clients/client74/web477/web/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/functions.php:426
Stack trace:
#0 /var/www/clients/client74/web477/web/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/functions.php(426): DateTime->__construct()
#1 /var/www/clients/client74/web477/web/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueCleaner.php(34): as_get_datetime_object()
#2 /var/www/clients/client74/web477/web/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueCleaner.php(139): ActionScheduler_QueueCleaner->delete_old_actions()
#3 /var/www/clients/client74/web477/web/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(160):  in /var/www/clients/client74/web477/web/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/functions.php on line 426`

**Comment by barryhughes** [comment] 2023-03-21 19:23
Thanks, it's somewhat useful: it tells us that the problem occurs in the Queue Cleaner, when [calculating the retention period](https://github.com/woocommerce/action-scheduler/blob/3.5.4/classes/ActionScheduler_QueueCleaner.php#L33-L34):

```php
$lifespan = apply_filters( 'action_scheduler_retention_period', $this->month_in_seconds );
$cutoff = as_get_datetime_object($lifespan.' seconds ago');
```

The value of [$this->month_in_seconds](https://github.com/woocommerce/action-scheduler/blob/3.5.4/classes/ActionScheduler_QueueCleaner.php#L19) defaults to `2678400` so some code, somewhere (but not necessarily in SEO by Rank Math) is overriding that and presumably setting it to an empty string, or to null.

As it happens, we recently merged a change that [addresses this issue](https://github.com/woocommerce/action-scheduler/pull/923/), and will be included in the next release.

**Closed as completed by barryhughes** 2023-03-21 19:23 UTC
Labels: type: bug, priority: normal, needs feedback
