### ISSUE TITLE
Uncaught RuntimeException: Unable to claim actions. Database error

### ISSUE THREAD

**Issue by DevKishan** [Prospress/action-scheduler#872] opened 2022-10-18 11:05 UTC
I am using the **Action Scheduler** library **3.3.0** version in my plugin and getting this error
```

Uncaught RuntimeException: Unable to claim actions. Database error . in public_html/wp-content/plugins/my-plugin/includes/libraries/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:683Stack trace:

#0 /home/public_html/wp-content/plugins/my-plugin/includes/libraries/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php(597): ActionScheduler_DBStore->claim_actions(2419127, 25, NULL, Array, '')
#1 /home/public_html/wp-content/plugins/my-plugin/includes/libraries/action-scheduler/classes/ActionScheduler_QueueRunner.php(153): ActionScheduler_DBStore->stake_claim(25)
#2 /home/public_html/wp-content/plugins/my-plugin/includes/libraries/action-scheduler/classes/ActionScheduler_QueueRunner.php(132): ActionScheduler_QueueRunner->do_batch(25, 'WP Cron')
#3 /home/public_html/wp-includes/class-wp-hook.php(307): ActionScheduler_QueueRunner->run('WP Cron')
#4 in /home/public_html/wp-content/plugins/my-plugin/includes/libraries/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 683
```
Here in [704](https://github.com/woocommerce/action-scheduler/issues/704#issuecomment-861571135)  thread, it is suggested that upgrading to version **3.2.0** should help in fixing the issue, but I am using **version 3.3.0** and still getting the issue. 

Any idea why this happening and how to fix it? 
Is this because of race conditions as mentioned in the #793 thread?

**Comment by arnaudbroes** [comment] 2022-10-18 21:39
At AIOSEO we're also getting [reports ](https://wordpress.org/support/topic/fatal-error-4269/) of this. We're using version 3.4.2 at the moment. One of the other teams in our company that develops WP Mail SMTP is [also affected](https://wordpress.org/support/topic/missing-tables-uncaught-runtimeexception-unable-to-claim-actions-db-error/).

**Comment by jorgeatorres** [comment] 2022-10-25 23:39
Hi @DevKishan @arnaudbroes,

Thanks for the report. Let's try to get you up and running here.

Under certain circumstances, when you have a couple of plugins running different AS versions, it could happen that the latest one isn't the one necessarily in use. We have a guide on de-conflicting that could help you both here: https://developer.woocommerce.com/2021/10/12/best-practices-for-deconflicting-different-versions-of-action-scheduler/. Could that be what's going on here?

Now, if you're definitely certain that 3.3.0/3.4.2 is the version being used, could you please share some more details on your setup? Are there any MySQL errors showing up in the logs? Do you know if there are other AS-using plugins on the site?

**Comment by arnaudbroes** [comment] 2022-10-26 20:43
> Do you know if there are other AS-using plugins on the site?

I'm not certain. I've asked the user and will follow up here once I know more. I figured I'd just comment on this issue since I've seen this error occur on a few sites in the past few weeks. Seemed like a trend to me, but might be a coincidence.

**Comment by arnaudbroes** [comment] 2022-11-01 12:46
@jorgeatorres it looks like the user is using version 3.5.2 (version used in AIOSEO is 3.4.2). He has posted a dump of his environment and active plugins here - https://wordpress.org/support/topic/fatal-error-4269/

**Comment by DevKishan** [comment] 2022-11-10 11:04
@jorgeatorres 

> Under certain circumstances, when you have a couple of plugins running different AS versions, it could happen that the latest one isn't the one necessarily in use.

In WooCommerce's system status page, it shows **Action Scheduler 3.5.2** version is in use which is coming from **wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler**. Our plugin ships with the **3.3.0** version.

> Are there any MySQL errors showing up in the logs? 

Currently, there aren't any MySQL errors showing in the logs.

> Do you know if there are other AS-using plugins on the site?

Yes, currently seo-by-rank-math plugin is also using AS library.

**Comment by jorgeatorres** [comment] 2022-11-29 18:21
Hi @DevKishan @arnaudbroes!

We haven't been able to reproduce this, but after looking more carefully at the stacktraces you've shared (also the one @arnaudbroes linked to) we can see that, in fact, there appears to be a conflict between AS versions (bundled with some of the active plugins).

For example:

- The system report @arnaudbroes shared, indicates the user is running AS 3.5.2 but line 683 of `ActionScheduler_DBStore` (where the exception is coming) [is just a comment](https://github.com/woocommerce/action-scheduler/blob/3.5.2/classes/data-stores/ActionScheduler_DBStore.php#L683). It is, however, an exception [in version 3.4.2](https://github.com/woocommerce/action-scheduler/blob/3.4.2/classes/data-stores/ActionScheduler_DBStore.php#L683). So there seems to be a conflict as the report indicates the site runs 3.5.2 but it seems to be actually running code from 3.4.2 (the version in AIOSEO probably).
- Similarly, @DevKishan, in the case you've shared: status indicates 3.5.2 is running but that can't possibly be if the exception is being generated there. Even if your plugin ships with 3.3.0, that's also not the version in use as in 3.3.0 [the problematic line](https://github.com/woocommerce/action-scheduler/blob/3.3.0/classes/data-stores/ActionScheduler_DBStore.php#L683) is just a closing brace `}`.

So I must insist in trying to debug a possible conflict of versions, as those sites don't seem to be running the versions shipped with you respective plugins and the system report is clearly not picking up whatever version is actually being run.

As I said before, we have some docs on deconflicting versions of AS (https://developer.woocommerce.com/2021/10/12/best-practices-for-deconflicting-different-versions-of-action-scheduler/), but maybe some careful activating/deactivating of plugins can help pinpoint the plugin that is "taking over" AS (despite what the system report indicates).

Please let us know how this goes and we'll take it from there.

**Closed as completed** 2023-01-25 19:28 UTC
Labels: needs feedback
