### ISSUE TITLE
Any idea what caused the error?

### ISSUE THREAD

**Issue by markgabinete** [Prospress/action-scheduler#882] opened 2022-11-02 11:08 UTC
Hi, we have encountered this issue:
PHP Fatal error:  Uncaught InvalidArgumentException: Unidentified action 1161478 in /home/dapsmagic/public_html/wp-content/plugins/internal-links/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:926
![image](https://user-images.githubusercontent.com/60727346/199474542-71395e0d-ffc2-4d46-9015-ae1d596456e0.png)

Any ideas what could cause this and how can we prevent it?

Thank you

**Comment by barryhughes** [comment] 2022-11-02 18:40
Hi @markgabinete,

Our best guess is that an unexpected race condition resulted in one of your actions being removed by one process, before the queue runner (in a different process) could properly process it. We were curious:

- How often do you see this error?
- As far as you can tell, is the backlog of scheduled actions still being processed successfully?

**Comment by markgabinete** [comment] 2022-11-02 19:41
Unexpected race condition? I'm not sure what it is? could you give an example?
The scheduled actions are being hindered and failing due to the issue in one of our client's site, so I may say that this does not happen to all sites as I'm not able to replicate this but some client's of ours got this errors and the actions are not able to process successfully.
Thank you

**Comment by barryhughes** [comment] 2022-11-02 20:00
> Unexpected race condition? I'm not sure what it is? could you give an example?

Action Scheduler periodically creates Queue Runners, which will then claim a set of actions and start processing them. Ideally, for as long as the claim is valid, no other processes would directly interact with that set of actions—but it's not impossible.

Suppose a queue runner begins to process an individual action, but simultaneously some other process also starts to process it, or deletes it, it could cause a problem like the one you have described.

> The scheduled actions are being hindered and failing due to the issue in one of our client's site, so I may say that this does not happen to all sites

On the impacted site, do you know which plugins are using Action Scheduler, and have you been able to determine if a specific plugin needs to be present to see the problem?

**Comment by markgabinete** [comment] 2022-11-03 10:38
We are unable to single out the specific plugin that may have caused this as we have no control over the sites.
But we know this specific site have plugins that uses action scheduler like WP rocket and a plugin that generates "woocommerce_update_marketplace_suggestions" scheduled action(not woocommerce as they don't have it on the site).
Also they have this plugin "Publish to Apple News" but they use cron events could cron events also contribute to this issue?

**Comment by markgabinete** [comment] 2022-11-03 11:11
Also related issue, the site tends to be stuck on scheduled actions not failing or completing for hours.
What is strange is there are still schedule actions from our plugin that completes and some fails.
![image](https://user-images.githubusercontent.com/60727346/199705755-47e0b1f8-fb26-4a90-8b78-6392703d877d.png)
There  seems to be a  300 seconds timeout but no specific issue logged on the error log for this

**Comment by barryhughes** [comment] 2022-11-03 18:44
On the last point, when you see `action marked as failed after 300 seconds`, that tends to mean the Queue Cleaner has detected actions that seem to be stuck (that is, their status is still `in-progress` even after 5 minutes have elapsed). It then marks the actions as failed, and logs this message. 

- It's possible these actions are genuinely still running, but that would be unusual in most cases (do you know what these actions are for?)
- More likely, the action has led to an error—perhaps a fatal error that the queue runner could not recover from—and were subsequently left in an incomplete state.

Do these log entries tie up with the fatal errors you are seeing in the logs/are there any other logged errors that correlate with these events?

**Comment by barryhughes** [comment] 2022-11-03 18:47
I should also highlight: in many regards Action Scheduler is just the 'vehicle' through which code from other plugins can run. 

So, if Plugin X sets up a scheduled action, and its callback consistently causes a fatal error or runs until the process times out, etc, then there isn't a lot Action Scheduler can do to handle that. For that reason, it may also be worth starting a conversation with the relevant plugin vendor(s) if you have not already done so.

**Comment by markgabinete** [comment] 2022-11-04 03:55
Yes the logs are correlated to these failed events. The failed events are our plugin's scheduled action and they encountered action marked as failed after 300 seconds error, does this means that the process is taken too long and this cause the action to be stuck? We do internal linking so maybe the site is too big for the process to action fully?
Because there is no other error regarding the action of our plugin functions as we cannot encounter on some of our sites.

**Comment by barryhughes** [comment] 2022-11-08 13:27
> Does this means that the process is taken too long.

That's one possibility, another could be that they (inadvertently) end execution, and so the job status is not updated, until later when cleanup takes place and they are marked as failed.

> The failed events are our plugin's scheduled action.

Given that, are there opportunities to introduce logging to see how far into your callback things are progressing? For instance, if you had a trivial callback looking something like:

```php
function my_callback() {
    do_one_thing();
    do_another_thing();
}
```

Could you update it to:

```php
function my_callback() {
    log( time, 'my_callback.before_do_one_thing' );
    do_one_thing();

    log( time, 'my_callback.before_do_another_thing' );
    do_another_thing();

    log( time, 'my_callback.completed' );
}
```

If, in my example, we noticed a general trend in which everything being logged except for the final `my_callback.completed` event, then that would steer us toward looking at function `do_another_thing()`.

**Comment by barryhughes** [comment] 2022-11-29 00:15
Since there has been no further follow-up (and we were unable to identify a set of steps to reproduce outside of your environment), I will go ahead and close this issue. Thanks!

**Closed as completed by barryhughes** 2022-11-29 00:15 UTC
Labels: needs feedback
