### ISSUE TITLE
CRITICAL Uncaught InvalidArgumentException: The group "rocket-rucss" does not exist.

### ISSUE THREAD

**Issue by alewolf** [Prospress/action-scheduler#972] opened 2023-08-02 06:56 UTC
On some installs, our users get a `CRITICAL Uncaught InvalidArgumentException: The group "rocket-rucss" does not exist.` error. 

This might be related to https://github.com/woocommerce/action-scheduler/issues/882 and https://github.com/woocommerce/action-scheduler/issues/970.

This should be fixed or a safeguard built in to prevent the critical error.

Here's the error log: 

```
2023-08-02T00:02:12+00:00 CRITICAL Uncaught InvalidArgumentException: The group "rocket-rucss" does not exist. in /usr/www/users/redacted/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:907
Stack trace:
#0 /usr/www/users/redacted/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php(799): ActionScheduler_DBStore->claim_actions(392029, 25, NULL, '', 'rocket-rucss')
#1 /usr/www/users/redacted/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueRunner.php(157): ActionScheduler_DBStore->stake_claim(25)
#2 /usr/www/users/redacted/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueRunner.php(136): ActionScheduler_QueueRunner->do_batch(25, 'WP Cron')
#3 /usr/www/users/redacted/wp-includes/class-wp-hook.php(307): ActionScheduler_QueueRunner->run('WP Cron')
#4 /usr/www/users/redacted/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /usr/www/users/redacted/wp-includes/plugin.php(522): WP_Hook->do_action(Array)
#6 /usr/www/users/redacted/wp-cron.php(138): do_action_ref_array('action_schedule...', Array)
#7 {main}
  thrown in /usr/www/users/redacted/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 907
```

**Comment by rrennick** [comment] 2023-08-03 18:18
@alewolf Thanks for reporting the issue. By default Action Scheduler does not filter by groups when running actions. 

However, if you install [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/) you may be able to find the offending cron job and delete it. If you have recently removed or deactivated a plugin then look for a cron job associated with that plugin.

We'll leave this issue open as a reminder to evaluate how to handle this exception.

**Comment by alewolf** [comment] 2023-08-03 19:11
@rrennick This was reported to me by a user of my plugin, the Pixel Manager for WooCommerce `/woocommerce-google-adwords-conversion-tracking-tag/`. 

I can't replicate the error because it doesn't occur on my installs. 

The way the Action Scheduler works, it can be a third-party plugin triggering the error.  But the Action Scheduler is executed from the Pixel Manager folder because I pack the newest version, so the error log shows `/woocommerce-google-adwords-conversion-tracking-tag/`. 

That's why I get the support requests. I assume many other users are blaming the Pixel Manager without telling me. 

I'm considering downgrading the Action Scheduler version in the Pixel Manager to one version lower than the one packed with WooCommerce to avoid that problem and redirect support requests to WooCommerce that way. But that would not be a good solution on a larger scale.

**Comment by rrennick** [comment] 2023-08-03 20:03
@alewolf Thanks for the quick follow up. Can you ask one of the customers for their Woo SSR? Hopefully the rocket-rucss slug will point to an inactive plugin in their install.

**Comment by alewolf** [comment] 2023-08-03 20:11
@rrennick What do you mean by "Woo SSR" ?

**Comment by piotrbak** [comment] 2023-08-04 10:23
@alewolf @rrennick `rocket-rucss` is related to WP Rocket plugin:
https://github.com/wp-media/wp-rocket/blob/901911571c027b0b4a5979651a52ef3c0edfbe5f/inc/Engine/Optimization/RUCSS/Controller/Queue.php#L22

I'd suggest asking customer to contact our Support Team, I can see that we had one case like this in the pas but we were not able to reproduce this problem. If it's reproducible, it would be great to provide us access to this website.

**Comment by rrennick** [comment] 2023-08-04 15:05
@alewolf Sorry, SSR refers to the Woo System Status Report.

@piotrbak Thanks for chiming in on this one.

**Comment by alewolf** [comment] 2023-08-05 06:08
@piotrbak @rrennick I've sent our customer the link to this issue and encouraged him to contact you.

**Comment by sagestephens** [comment] 2023-08-10 05:59
Hi I am the customer with the issue do you need my website link?

**Comment by barryhughes** [comment] 2023-08-14 22:00
@sagestephens (and @alewolf), we're a little confused as to what is happening here. Flipping the backtrace upside down, here are how things seem to be unfolding:

```
#6 /usr/www/users/redacted/wp-cron.php(138): 
do_action_ref_array('action_schedule...', Array)
```

☝🏼 We basically [start here](https://github.com/WordPress/wordpress-develop/blob/6.3.0/src/wp-cron.php#L191), inside WP's cron code. This means WordPress is in the middle of processing any [scheduled events](https://developer.wordpress.org/plugins/cron/understanding-wp-cron-scheduling/) that have been registered and, in this case, that seems to mean the Action Scheduler queue runner event.

```
#3 /usr/www/users/redacted/wp-includes/class-wp-hook.php(307): 
ActionScheduler_QueueRunner->run('WP Cron')
```

☝🏼 I think we can skip a few entries until [we get here](https://github.com/woocommerce/action-scheduler/blob/3.6.2/classes/ActionScheduler_QueueRunner.php#L129). Note that this method only accepts **one** parameter (the context, which in this case will be `'wp-cron'`).

```#2 /usr/www/users/redacted/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueRunner.php(136): 
ActionScheduler_QueueRunner->do_batch(25, 'WP Cron')
```

:point_up: Next, the [`do_batch()`](https://github.com/woocommerce/action-scheduler/blob/3.6.2/classes/ActionScheduler_QueueRunner.php#L159) method is called, which then tries to 'stake a claim'.

```
#1 /usr/www/users/redacted/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueRunner.php(157): 
ActionScheduler_DBStore->stake_claim(25)
```
:point_up: Here we are, [staking a claim](https://github.com/woocommerce/action-scheduler/blob/3.6.2/classes/ActionScheduler_QueueRunner.php#L160) and the only information we pass is the number of actions we want to claim (25, based on the backtrace).

```
#0 /usr/www/users/redacted/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php(799):
ActionScheduler_DBStore->claim_actions(392029, 25, NULL, '', 'rocket-rucss')
```

:point_up: Closing in on the point-of-failure, when we try to claim the actual actions the default behavior would be to not specify any group [(see code here)](https://github.com/woocommerce/action-scheduler/blob/3.6.2/classes/data-stores/ActionScheduler_DBStore.php#L799) yet the backtrace tells us `rocket-rucss` is being specified.

This is what's confusing us (ie, where is `rocket-rucss` coming from) ... is it possible that this code was manually modified? If (@sagestephens) you re-install `woocommerce-google-adwords-conversion-tracking-tag` from source, does the same problem persist?

**Comment by PanosSynetos** [comment] 2023-08-30 07:08
We have another report of the same issue in https://wordpress.org/support/topic/customers-is-not-working/#post-17011606

> InvalidArgumentException: Группы «rocket-rucss» не существует. 
> InvalidArgumentException: Group 'rocket-rucss' does not exist.

`rocket-rucss` is coming from WP Rocket as @piotrbak mentioned about a month ago

https://github.com/wp-media/wp-rocket/blob/901911571c027b0b4a5979651a52ef3c0edfbe5f/inc/Engine/Optimization/RUCSS/Controller/Queue.php#L22

```
2023-08-30T00:19:30+00:00 CRITICAL Uncaught InvalidArgumentException: Группы «rocket-rucss» не существует. in /var/www/u1894878/data/www/studio-parfum.ru/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:907
Stack trace:
#0 /var/www/u1894878/data/www/studio-parfum.ru/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php(799): ActionScheduler_DBStore->claim_actions(9761, 25, NULL, '', 'rocket-rucss')
#1 /var/www/u1894878/data/www/studio-parfum.ru/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(157): ActionScheduler_DBStore->stake_claim(25)
#2 /var/www/u1894878/data/www/studio-parfum.ru/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(136): ActionScheduler_QueueRunner->do_batch(25, 'WP Cron')
#3 /var/www/u1894878/data/www/studio-parfum.ru/wp-includes/class-wp-hook.php(310): ActionScheduler_QueueRunner->run('WP Cron')
#4 /var/www/u1894878/data/www/studio-parfum.ru/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#5 /var/www/u1894878/data/www/studio-parfum.ru/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#6 /var/www/u1894878/data/www/studio-parfum.ru/wp-cron.php(191): do_action_ref_array('action_schedule...', Array)
#7 {main}
  thrown в /var/www/u1894878/data/www/studio-parfum.ru/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php на строке 907
```

**Comment by barryhughes** [comment] 2023-08-31 16:47
Thanks, @PanosSynetos. I somehow missed (or misinterpreted) @piotrbak's note. Given this is the result of a [custom queue runner](https://github.com/wp-media/wp-rocket/blob/901911571c027b0b4a5979651a52ef3c0edfbe5f/inc/Engine/Common/Queue/RUCSSQueueRunner.php#L195-L223), it seems appropriate to close this (the raised exception does not seem inappropriate to me). For anyone else experiencing this problem, please do reach out to the WP Rocket team.

**Closed as completed by barryhughes** 2023-08-31 16:47 UTC
Labels: needs feedback, type: task, type: technical debt

**Comment by engahmeds3ed** [comment] 2023-09-05 13:52
@barryhughes @rrennick 

May I ask why here:

https://github.com/woocommerce/action-scheduler/blob/8643e7fbca68d1927a00b2591cea66b7925b3bf6/classes/data-stores/ActionScheduler_DBStore.php#L903

$create_if_not_exists argument is false?

**Comment by barryhughes** [comment] 2023-09-05 18:59
Hi @engahmeds3ed,

This method is responsible for *claiming* actions. So, I'd flip the question around: if the specified group or groups do not already exist, and so there are no actions to be claimed, why would we create one or more empty groups? It doesn't feel to me like a step the claiming process should take.

Building on that, my initial thoughts are that it seems reasonable for us to avoid creating empty groups and also that it is the responsibility of any custom code calling this method to anticipate and catch any exceptions it might throw.

Let me know your thoughts (though, Ron may also have valuable input to add on this one).

**Comment by rrennick** [comment] 2023-09-05 19:08
> Ron may also have valuable input to add on this one

I agree. We should not be creating groups during the claim process.

**Comment by engahmeds3ed** [comment] 2023-09-05 19:32
That's a valid point, thanks @barryhughes @rrennick for taking time explaining that.

**Comment by engahmeds3ed** [comment] 2023-09-06 11:59
After some investigation about this issue, let me share with u my findings so u can decide if we need to fix that in action Scheduler's core or not.

Assume we have a custom queue runner like [this one](https://github.com/wp-media/wp-rocket/blob/e98eb93e55d55bb7d2ad4310ab59d2e69bc97a72/inc/Engine/Common/Queue/RUCSSQueueRunner.php#L63-L85) and as u see, there we are not setting the store object so it's null exactly like the default queue runner [here](https://github.com/woocommerce/action-scheduler/blob/d1a5342a3ff80b07e97432d3f652f8c61beb816f/classes/ActionScheduler_QueueRunner.php#L39-L47)
and both (custom runner and default runner) are running every_minute.

So Based on [that code](https://github.com/woocommerce/action-scheduler/blob/d46040b02d21c054ef7193a24cf2b76c39d1cde2/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L38), both runners will share the store instance (because it's singleton design pattern).

What happens here is that the custom runner is running before the default runner passing the group to the store `stake_claim` method [here](https://github.com/wp-media/wp-rocket/blob/e98eb93e55d55bb7d2ad4310ab59d2e69bc97a72/inc/Engine/Common/Queue/RUCSSQueueRunner.php#L197)

and based on [that code](https://github.com/woocommerce/action-scheduler/blob/8643e7fbca68d1927a00b2591cea66b7925b3bf6/classes/data-stores/ActionScheduler_DBStore.php#L880-L884) that was added in this [pull request](https://github.com/woocommerce/action-scheduler/pull/905) you are setting the group item inside claim_filters and as we use the same object for store in both queue runners, the group will be kept the one that added in the custom queue runner.

You can also check the following full backtrace:

```
array (
  0 => 
  array (
    'file' => '/var/www/html/wordpress/wp-content/plugins/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php',
    'line' => 799,
    'function' => 'claim_actions',
    'class' => 'ActionScheduler_DBStore',
    'object' => 
    ActionScheduler_DBStore::__set_state(array(
       'claim_before_date' => NULL,
       'claim_filters' => 
      array (
        'group' => 'rocket-rucss',
        'hooks' => '',
        'exclude-groups' => '',
      ),
    )),
    'type' => '->',
    'args' => 
    array (
      0 => 13316,
      1 => 25,
      2 => NULL,
      3 => '',
      4 => 'rocket-rucss',
    ),
  ),
  1 => 
  array (
    'file' => '/var/www/html/wordpress/wp-content/plugins/action-scheduler/classes/ActionScheduler_QueueRunner.php',
    'line' => 160,
    'function' => 'stake_claim',
    'class' => 'ActionScheduler_DBStore',
    'object' => 
    ActionScheduler_DBStore::__set_state(array(
       'claim_before_date' => NULL,
       'claim_filters' => 
      array (
        'group' => 'rocket-rucss',
        'hooks' => '',
        'exclude-groups' => '',
      ),
    )),
    'type' => '->',
    'args' => 
    array (
      0 => 25,
    ),
  ),
  2 => 
  array (
    'file' => '/var/www/html/wordpress/wp-content/plugins/action-scheduler/classes/ActionScheduler_QueueRunner.php',
    'line' => 139,
    'function' => 'do_batch',
    'class' => 'ActionScheduler_QueueRunner',
    'object' => 
    ActionScheduler_QueueRunner::__set_state(array(
       'async_request' => 
      ActionScheduler_AsyncRequest_QueueRunner::__set_state(array(
         'store' => 
        ActionScheduler_DBStore::__set_state(array(
           'claim_before_date' => NULL,
           'claim_filters' => 
          array (
            'group' => 'rocket-rucss',
            'hooks' => '',
            'exclude-groups' => '',
          ),
        )),
         'prefix' => 'as',
         'action' => 'async_request_queue_runner',
         'identifier' => 'as_async_request_queue_runner',
         'data' => 
        array (
        ),
      )),
       'processed_actions_count' => 0,
       'cleaner' => 
      ActionScheduler_QueueCleaner::__set_state(array(
         'batch_size' => 20,
         'store' => 
        ActionScheduler_DBStore::__set_state(array(
           'claim_before_date' => NULL,
           'claim_filters' => 
          array (
            'group' => 'rocket-rucss',
            'hooks' => '',
            'exclude-groups' => '',
          ),
        )),
         'month_in_seconds' => 2678400,
         'default_statuses_to_purge' => 
        array (
          0 => 'complete',
          1 => 'canceled',
        ),
      )),
       'monitor' => 
      ActionScheduler_FatalErrorMonitor::__set_state(array(
         'claim' => NULL,
         'store' => 
        ActionScheduler_DBStore::__set_state(array(
           'claim_before_date' => NULL,
           'claim_filters' => 
          array (
            'group' => 'rocket-rucss',
            'hooks' => '',
            'exclude-groups' => '',
          ),
        )),
         'action_id' => 0,
      )),
       'store' => 
      ActionScheduler_DBStore::__set_state(array(
         'claim_before_date' => NULL,
         'claim_filters' => 
        array (
          'group' => 'rocket-rucss',
          'hooks' => '',
          'exclude-groups' => '',
        ),
      )),
       'created_time' => 1693943820.477584,
    )),
    'type' => '->',
    'args' => 
    array (
      0 => 25,
      1 => 'WP Cron',
    ),
  ),
  3 => 
  array (
    'file' => '/var/www/html/wordpress/wp-includes/class-wp-hook.php',
    'line' => 308,
    'function' => 'run',
    'class' => 'ActionScheduler_QueueRunner',
    'object' => 
    ActionScheduler_QueueRunner::__set_state(array(
       'async_request' => 
      ActionScheduler_AsyncRequest_QueueRunner::__set_state(array(
         'store' => 
        ActionScheduler_DBStore::__set_state(array(
           'claim_before_date' => NULL,
           'claim_filters' => 
          array (
            'group' => 'rocket-rucss',
            'hooks' => '',
            'exclude-groups' => '',
          ),
        )),
         'prefix' => 'as',
         'action' => 'async_request_queue_runner',
         'identifier' => 'as_async_request_queue_runner',
         'data' => 
        array (
        ),
      )),
       'processed_actions_count' => 0,
       'cleaner' => 
      ActionScheduler_QueueCleaner::__set_state(array(
         'batch_size' => 20,
         'store' => 
        ActionScheduler_DBStore::__set_state(array(
           'claim_before_date' => NULL,
           'claim_filters' => 
          array (
            'group' => 'rocket-rucss',
            'hooks' => '',
            'exclude-groups' => '',
          ),
        )),
         'month_in_seconds' => 2678400,
         'default_statuses_to_purge' => 
        array (
          0 => 'complete',
          1 => 'canceled',
        ),
      )),
       'monitor' => 
      ActionScheduler_FatalErrorMonitor::__set_state(array(
         'claim' => NULL,
         'store' => 
        ActionScheduler_DBStore::__set_state(array(
           'claim_before_date' => NULL,
           'claim_filters' => 
          array (
            'group' => 'rocket-rucss',
            'hooks' => '',
            'exclude-groups' => '',
          ),
        )),
         'action_id' => 0,
      )),
       'store' => 
      ActionScheduler_DBStore::__set_state(array(
         'claim_before_date' => NULL,
         'claim_filters' => 
        array (
          'group' => 'rocket-rucss',
          'hooks' => '',
          'exclude-groups' => '',
        ),
      )),
       'created_time' => 1693943820.477584,
    )),
    'type' => '->',
    'args' => 
    array (
      0 => 'WP Cron',
    ),
  ),
  4 => 
  array (
    'file' => '/var/www/html/wordpress/wp-includes/class-wp-hook.php',
    'line' => 332,
    'function' => 'apply_filters',
    'class' => 'WP_Hook',
    'object' => 
    WP_Hook::__set_state(array(
       'callbacks' => 
      array (
        10 => 
        array (
          '000000000b907149000000004766d3efrun' => 
          array (
            'function' => 
            array (
              0 => 
              ActionScheduler_QueueRunner::__set_state(array(
                 'async_request' => 
                ActionScheduler_AsyncRequest_QueueRunner::__set_state(array(
                   'store' => 
                  ActionScheduler_DBStore::__set_state(array(
                     'claim_before_date' => NULL,
                     'claim_filters' => 
                    array (
                      'group' => 'rocket-rucss',
                      'hooks' => '',
                      'exclude-groups' => '',
                    ),
                  )),
                   'prefix' => 'as',
                   'action' => 'async_request_queue_runner',
                   'identifier' => 'as_async_request_queue_runner',
                   'data' => 
                  array (
                  ),
                )),
                 'processed_actions_count' => 0,
                 'cleaner' => 
                ActionScheduler_QueueCleaner::__set_state(array(
                   'batch_size' => 20,
                   'store' => 
                  ActionScheduler_DBStore::__set_state(array(
                     'claim_before_date' => NULL,
                     'claim_filters' => 
                    array (
                      'group' => 'rocket-rucss',
                      'hooks' => '',
                      'exclude-groups' => '',
                    ),
                  )),
                   'month_in_seconds' => 2678400,
                   'default_statuses_to_purge' => 
                  array (
                    0 => 'complete',
                    1 => 'canceled',
                  ),
                )),
                 'monitor' => 
                ActionScheduler_FatalErrorMonitor::__set_state(array(
                   'claim' => NULL,
                   'store' => 
                  ActionScheduler_DBStore::__set_state(array(
                     'claim_before_date' => NULL,
                     'claim_filters' => 
                    array (
                      'group' => 'rocket-rucss',
                      'hooks' => '',
                      'exclude-groups' => '',
                    ),
                  )),
                   'action_id' => 0,
                )),
                 'store' => 
                ActionScheduler_DBStore::__set_state(array(
                   'claim_before_date' => NULL,
                   'claim_filters' => 
                  array (
                    'group' => 'rocket-rucss',
                    'hooks' => '',
                    'exclude-groups' => '',
                  ),
                )),
                 'created_time' => 1693943820.477584,
              )),
              1 => 'run',
            ),
            'accepted_args' => 1,
          ),
        ),
      ),
       'iterations' => 
      array (
        0 => 
        array (
          0 => 10,
        ),
      ),
       'current_priority' => 
      array (
        0 => 10,
      ),
       'nesting_level' => 1,
       'doing_action' => true,
    )),
    'type' => '->',
    'args' => 
    array (
      0 => '',
      1 => 
      array (
        0 => 'WP Cron',
      ),
    ),
  ),
  5 => 
  array (
    'file' => '/var/www/html/wordpress/wp-includes/plugin.php',
    'line' => 565,
    'function' => 'do_action',
    'class' => 'WP_Hook',
    'object' => 
    WP_Hook::__set_state(array(
       'callbacks' => 
      array (
        10 => 
        array (
          '000000000b907149000000004766d3efrun' => 
          array (
            'function' => 
            array (
              0 => 
              ActionScheduler_QueueRunner::__set_state(array(
                 'async_request' => 
                ActionScheduler_AsyncRequest_QueueRunner::__set_state(array(
                   'store' => 
                  ActionScheduler_DBStore::__set_state(array(
                     'claim_before_date' => NULL,
                     'claim_filters' => 
                    array (
                      'group' => 'rocket-rucss',
                      'hooks' => '',
                      'exclude-groups' => '',
                    ),
                  )),
                   'prefix' => 'as',
                   'action' => 'async_request_queue_runner',
                   'identifier' => 'as_async_request_queue_runner',
                   'data' => 
                  array (
                  ),
                )),
                 'processed_actions_count' => 0,
                 'cleaner' => 
                ActionScheduler_QueueCleaner::__set_state(array(
                   'batch_size' => 20,
                   'store' => 
                  ActionScheduler_DBStore::__set_state(array(
                     'claim_before_date' => NULL,
                     'claim_filters' => 
                    array (
                      'group' => 'rocket-rucss',
                      'hooks' => '',
                      'exclude-groups' => '',
                    ),
                  )),
                   'month_in_seconds' => 2678400,
                   'default_statuses_to_purge' => 
                  array (
                    0 => 'complete',
                    1 => 'canceled',
                  ),
                )),
                 'monitor' => 
                ActionScheduler_FatalErrorMonitor::__set_state(array(
                   'claim' => NULL,
                   'store' => 
                  ActionScheduler_DBStore::__set_state(array(
                     'claim_before_date' => NULL,
                     'claim_filters' => 
                    array (
                      'group' => 'rocket-rucss',
                      'hooks' => '',
                      'exclude-groups' => '',
                    ),
                  )),
                   'action_id' => 0,
                )),
                 'store' => 
                ActionScheduler_DBStore::__set_state(array(
                   'claim_before_date' => NULL,
                   'claim_filters' => 
                  array (
                    'group' => 'rocket-rucss',
                    'hooks' => '',
                    'exclude-groups' => '',
                  ),
                )),
                 'created_time' => 1693943820.477584,
              )),
              1 => 'run',
            ),
            'accepted_args' => 1,
          ),
        ),
      ),
       'iterations' => 
      array (
        0 => 
        array (
          0 => 10,
        ),
      ),
       'current_priority' => 
      array (
        0 => 10,
      ),
       'nesting_level' => 1,
       'doing_action' => true,
    )),
    'type' => '->',
    'args' => 
    array (
      0 => 
      array (
        0 => 'WP Cron',
      ),
    ),
  ),
  6 => 
  array (
    'file' => '/var/www/html/wordpress/wp-cron.php',
    'line' => 188,
    'function' => 'do_action_ref_array',
    'args' => 
    array (
      0 => 'action_scheduler_run_queue',
      1 => 
      array (
        0 => 'WP Cron',
      ),
    ),
  ),
)
```

what do u think @barryhughes @rrennick ?

**Comment by rrennick** [comment] 2023-09-06 17:08
> So Based on [that code](https://github.com/woocommerce/action-scheduler/blob/d46040b02d21c054ef7193a24cf2b76c39d1cde2/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L38), both runners will share the store instance (because it's singleton design pattern).

@alewolf Simgletons are not shared among worker threads/processes. Each thread will have its own singleton.

**Comment by engahmeds3ed** [comment] 2023-09-06 18:46
I believe WP Cron is calling both of CRON schedules in the same thread/request.

List of crons are being fetched here:
https://github.com/WordPress/wordpress-develop/blob/240f914e4f4bc28bba0d0705ade7d08a45487350/src/wp-cron.php#L84

and then Core is looping on them here:
https://github.com/WordPress/wordpress-develop/blob/240f914e4f4bc28bba0d0705ade7d08a45487350/src/wp-cron.php#L191

I believe that's because both of them are running every minute and used `time()` so both are on the same thread already.

The trace is showing that.

**Comment by rrennick** [comment] 2023-09-06 19:39
> that was added in this https://github.com/woocommerce/action-scheduler/pull/905 you are setting the group item inside claim_filters

That PR only changes the WP CLI `run` command where the `context` is [`WP CLI`](https://github.com/woocommerce/action-scheduler/blob/trunk/classes/WP_CLI/ActionScheduler_WPCLI_QueueRunner.php#L107). The WP cron runner is https://github.com/woocommerce/action-scheduler/blob/trunk/classes/ActionScheduler_QueueRunner.php.

**Comment by rrennick** [comment] 2023-09-06 19:42
> I believe WP Cron is calling both of CRON schedules in the same thread/request.

@alewolf Also, you are getting sidetracked from the root issue which is that the AS group does not exist. The custom runner is trying to claim actions from that group.

**Comment by engahmeds3ed** [comment] 2023-09-06 20:21
> That PR only changes the WP CLI `run` command where the `context` is [`WP CLI`](https://github.com/woocommerce/action-scheduler/blob/trunk/classes/WP_CLI/ActionScheduler_WPCLI_QueueRunner.php#L107). The WP cron runner is https://github.com/woocommerce/action-scheduler/blob/trunk/classes/ActionScheduler_QueueRunner.php.

u changed in the store class here:
https://github.com/woocommerce/action-scheduler/pull/905/files#diff-187a2644998973fd6a8b8e9455ad006ad4d502273b21f76607137c7c0acf9f1bR861

> @alewolf Also, you are getting sidetracked from the root issue which is that the AS group does not exist. The custom runner is trying to claim actions from that group.

I know exactly what I'm saying, I'm not getting sidetracked at all, I'm very clear with full trace and every line of code.

Anyway, I'll stop here and fix this in our side by creating our own store, just consider this conversation if u want/need.

Thanks for ur time.

**Comment by rrennick** [comment] 2023-09-06 21:51
> u changed in the store class here:

The WP CLI classes are only loaded when the process is [WP CLI](https://actionscheduler.org/wp-cli/).
