### ISSUE TITLE
Catchable fatal error 

### ISSUE THREAD

**Issue by rezzz-dev** [Prospress/action-scheduler#86] opened 2017-08-03 15:35 UTC
I'm not sure exactly what is going on with this. I'm leaning towards some data issues at this point since I've been as this issue for a little bit now. This is all in a local dev environment obviously, but curious on any thoughts.

@thenbrent requested me to put this into this repo.

Error:
`Catchable fatal error: Argument 3 passed to ActionScheduler_Action::__construct() must be an instance of ActionScheduler_Schedule, instance of __PHP_Incomplete_Class given, called in /code/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 123 and defined in /code/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_Action.php on line 13 Call Stack: 0.0022 269840 1. {main}() /code/wp-admin/edit.php:0 0.6517 52877488 2. WP_List_Table->display() /code/wp-admin/edit.php:357 0.6554 52912816 3. WP_List_Table->display_rows_or_placeholder() /code/wp-admin/includes/class-wp-list-table.php:1141 0.6554 52912920 4. WP_Posts_List_Table->display_rows() /code/wp-admin/includes/class-wp-list-table.php:1213 0.6554 52915832 5. WP_Posts_List_Table->_display_rows() /code/wp-admin/includes/class-wp-posts-list-table.php:644 0.6557 52925224 6. WP_Posts_List_Table->single_row() /code/wp-admin/includes/class-wp-posts-list-table.php:662 0.6569 52929680 7. WP_List_Table->single_row_columns() /code/wp-admin/includes/class-wp-posts-list-table.php:1185 0.6577 52933184 8. WP_Posts_List_Table->column_default() /code/wp-admin/includes/class-wp-list-table.php:1305 0.6577 52933512 9. do_action() /code/wp-admin/includes/class-wp-posts-list-table.php:1152 0.6577 52934272 10. WP_Hook->do_action() /code/wp-includes/plugin.php:453 0.6577 52934368 11. WP_Hook->apply_filters() /code/wp-includes/class-wp-hook.php:323 0.6577 52935656 12. call_user_func_array:{/code/wp-includes/class-wp-hook.php:298}() /code/wp-includes/class-wp-hook.php:298 0.6577 52936432 13. ActionScheduler_AdminView->list_table_column_content() /code/wp-includes/class-wp-hook.php:298 0.6577 52936624 14. ActionScheduler_wpPostStore->fetch_action() /code/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_AdminView.php:165 0.6578 52937304 15. ActionScheduler_wpPostStore->make_action_from_post() /code/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php:99 0.6605 53165656 16. ActionScheduler_Action->__construct() /code/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php:123`

Here's the System Status Report
`
### WordPress Environment ###

Home URL: https://counter-culture-grow.kbox.site
Site URL: https://counter-culture-grow.kbox.site
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.8.1
PHP Version: 5.6.30
PHP Post Max Size: 100 MB
PHP Time Limit: 90
PHP Max Input Vars: 10000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (60) ###

Gravity Forms: by rocketgenius – 2.2.3
Native PHP Sessions for WordPress: by Pantheon – 0.6.1
404page - your smart custom 404 error page: by Peter Raschendorfer – 2.5
Advanced Custom Fields PRO: by Elliot Condon – 5.5.14
Better User Search: by Dale Higgs – 1.1.1
CCC Credit Memos: by Julie Spragg - Counter Culture Coffee – 0.1
CCC Shop Manager & Subscription Options: by Julie Spragg – 1.1.0
CCC Disable WP Email: by Kurt Schlatzer - Counter Culture Coffee – 0.1
CCC Disable WP Login Autocomplete: by Kurt Schlatzer - Counter Culture Coffee – 0.1
Kill WP Emojis: by Kurt Schlatzer - Counter Culture Coffee – 0.1
CCC Magento Order History: by  – 1.0.0
CCC Order History: by Julie Spragg - Counter Culture Coffee – 0.1
CCC Trimark URL Checkout change: by Julie Spragg - Counter Culture Coffee – 0.1
CCC UPS Settings for West: by Julie Spragg - Counter Culture Coffee – 0.1
Admin Columns: by AdminColumns.com – 3.0
CCC Wholesale Functionality: by Grow Development – 0.0.3
Custom Post Type UI: by WebDevStudios – 1.5.3
Disable Comments: by Samir Shah – 1.6
CCC Eventbrite Plugin: by Julie Spragg – 2.0
Flight by Canto: by Canto Inc – 1.3.2
Gravity Forms MailChimp Add-On: by rocketgenius – 4.2
Heartbeat Control: by Jeff Matson – 1.0.3
HTTP header improved security: by Carl Conrad – 2.0.1
In8Sync Customers: by In8 – 2.1.14
In8Sync Inventory: by In8 – 2.1.14
In8Sync Products: by In8 – 2.1.14
In8Sync Sales Orders: by In8 – 2.1.14
In8Sync - NetSuite WooCommerce Integration: by In8Sync – 2.1.14
Jazzapi: by Julie Spragg – 1.0
Members: by Justin Tadlock – 1.1.3
Pantheon Advanced Page Cache: by Pantheon – 0.1.5
Postman SMTP: by Jason Hendriks – 1.7.2
Relevanssi: by Mikko Saari – 3.5.10
UPS WooCommerce Shipping: by WooForce – 3.7.1
User Switching: by John Blackbourn – 1.0.9
Username Changer: by Daniel J Griffiths – 3.1.0
WooCommerce Subscriptions Remove Deprecation Handlers: by Prospress Inc. – 1.0
PO Field for Orders: by Julie Spragg – 1.0
WooChimp: by RightPress – 2.2.2
WooCommerce Advanced Pricing: by Jeroen Sormani – 1.0.5
WooCommerce AvaTax: by SkyVerge – 1.4.2
WooCommerce Catalog Visibility Options: by Lucas Stark – 3.0.1
WooCommerce Composite Products: by SomewhereWarm – 3.9.4
WooCommerce Conditional Shipping and Payments: by WooThemes – 1.2.5
WooCommerce Authorize.Net CIM Gateway: by SkyVerge – 2.6.3
WooCommerce Grid / List toggle: by jameskoster – 1.1.0
WooCommerce Multiple Customer Addresses: by Lagudi Domenico – 5.2
WooCommerce Shipment Tracking: by WooCommerce – 1.6.6
WooCommerce USPS Shipping: by WooCommerce – 4.4.6
WooCommerce Subscribe All the Things: by Prospress Inc. – 2.0.0-alpha
Subscription Reports for WooCommerce: by StoreApps – 1.8
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.0-beta
WooCommerce Subscriptions: by Prospress Inc. – 2.2.11
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
Yoast SEO Premium: by Team Yoast – 4.8
WP Crontrol: by John Blackbourn & contributors – 1.5
WP-Sweep: by Lester 'GaMerZ' Chan – 1.0.10
Yoast SEO: WooCommerce: by Team Yoast – 4.8
YITH WooCommerce Category Accordion Premium: by YITHEMES – 1.0.16

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop
Cart: #5 - /cart
Checkout: #6 - /checkout
My Account: #7 - /my-account

### Taxonomies ###

Product Types: composite (composite)
grouped (grouped)
simple (simple)

### Theme ###

Name: CCC Theme
Version: 1.0
Author URL: http://counterculturecoffee.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: ccc-theme/woocommerce/archive-product.php
ccc-theme/woocommerce/cart/cart-empty.php
ccc-theme/woocommerce/cart/cart.php
ccc-theme/woocommerce/checkout/form-checkout.php
ccc-theme/woocommerce/checkout/form-shipping.php
ccc-theme/woocommerce/checkout/terms.php
ccc-theme/woocommerce/checkout/thankyou.php
ccc-theme/woocommerce/content-product.php
ccc-theme/woocommerce/content-single-product.php
ccc-theme/woocommerce/emails/admin-cancelled-order.php
ccc-theme/woocommerce/emails/admin-failed-order.php
ccc-theme/woocommerce/emails/admin-new-order.php
ccc-theme/woocommerce/emails/customer-completed-order.php
ccc-theme/woocommerce/emails/customer-invoice.php
ccc-theme/woocommerce/emails/customer-new-account.php
ccc-theme/woocommerce/emails/customer-note.php
ccc-theme/woocommerce/emails/customer-on-hold-order.php
ccc-theme/woocommerce/emails/customer-processing-order.php
ccc-theme/woocommerce/emails/customer-refunded-order.php
ccc-theme/woocommerce/emails/customer-reset-password.php
ccc-theme/woocommerce/emails/email-addresses.php
ccc-theme/woocommerce/emails/email-customer-details.php
ccc-theme/woocommerce/emails/email-footer.php
ccc-theme/woocommerce/emails/email-header.php
ccc-theme/woocommerce/emails/email-order-details.php
ccc-theme/woocommerce/emails/email-order-items.php
ccc-theme/woocommerce/emails/email-styles.php
ccc-theme/woocommerce/emails/plain/admin-cancelled-order.php
ccc-theme/woocommerce/emails/plain/admin-failed-order.php
ccc-theme/woocommerce/emails/plain/admin-new-order.php
ccc-theme/woocommerce/emails/plain/customer-completed-order.php
ccc-theme/woocommerce/emails/plain/customer-invoice.php
ccc-theme/woocommerce/emails/plain/customer-new-account.php
ccc-theme/woocommerce/emails/plain/customer-note.php
ccc-theme/woocommerce/emails/plain/customer-on-hold-order.php
ccc-theme/woocommerce/emails/plain/customer-processing-order.php
ccc-theme/woocommerce/emails/plain/customer-refunded-order.php
ccc-theme/woocommerce/emails/plain/customer-reset-password.php
ccc-theme/woocommerce/emails/plain/email-addresses.php
ccc-theme/woocommerce/emails/plain/email-customer-details.php
ccc-theme/woocommerce/emails/plain/email-order-details.php
ccc-theme/woocommerce/emails/plain/email-order-items.php
ccc-theme/woocommerce/global/quantity-input.php
ccc-theme/woocommerce/loop/loop-start.php
ccc-theme/woocommerce/loop/no-products-found.php
ccc-theme/woocommerce/myaccount/dashboard.php
ccc-theme/woocommerce/myaccount/form-login.php
ccc-theme/woocommerce/myaccount/navigation.php
ccc-theme/woocommerce/single-product/add-to-cart/grouped.php
ccc-theme/woocommerce/single-product/product-image.php
ccc-theme/woocommerce/single-product/product-thumbnails.php
ccc-theme/woocommerce/single-product/short-description.php
ccc-theme/woocommerce/single-product/up-sells.php

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Authorize.Net CIM ###

Environment: Test
Tokenization Enabled: ✔
Debug Mode: Off
`

**Comment by crodas** [comment] 2017-08-03 15:37
`__PHP_Incomplete_Class` means that PHP is unserialising an object and its class definition cannot be found. I guess it is deserialising data too early before their autoloader is registered.

I will take a look.

**Comment by rezzz-dev** [comment] 2017-08-03 15:42
@crodas Whose autoloader?

**Comment by crodas** [comment] 2017-08-03 15:50
> @crodas Whose autoloader?

The autoloader of the serialised object. It is hard to tell just from the backtrace. As far as backtrace tells me, this error is happening in the admin when it is listing all the action scheduler entries.

**Comment by rezzz-dev** [comment] 2017-08-03 15:57
That's correct - https://cl.ly/0I05060u383z

This is what happens when in the admin and going to the Scheduled Actions screen.

**Comment by rezzz-dev** [comment] 2017-08-03 15:58
What else could I provide you with in order to diagnose this issue further?

**Comment by crodas** [comment] 2017-08-03 15:59
Is that happening in `master`? I'm working on a new admin view for the upcoming branch `custom_tables` that should be ready later today or tomorrow.

**Comment by rezzz-dev** [comment] 2017-08-03 16:00
Yes, this is happening in the latest version of WCS that's downloaded from woocommerce.com

**Comment by crodas** [comment] 2017-08-03 16:00
I will investigate now.

**Comment by rezzz-dev** [comment] 2017-08-03 16:01
Appreciate it @crodas

**Comment by crodas** [comment] 2017-08-03 16:08
@rezzz-dev can you please see the value of the post metadata `_action_manager_schedule` for the $post which is giving you issues? If you don't know which ID is giving you issue, you can add a `var_dump($post->ID);` in [here](https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_wpPostStore.php#L116)

**Comment by rezzz-dev** [comment] 2017-08-03 16:19
Here you go

O:19:"GD_CCC_CronSchedule":2:{s:36:"GD_CCC_CronSchedulestart_timestamp";s:10:"1499096991";s:25:"GD_CCC_CronSchedulecron";O:14:"CronExpression":2:{s:25:"CronExpressioncronParts";a:5:{i:0;s:6:"5-60/2";i:1;s:3:"5-9";i:2;s:1:"*";i:3;s:1:"*";i:4;s:1:"*";}s:28:"CronExpressionfieldFactory";O:27:"CronExpression_FieldFactory":1:{s:35:"CronExpression_FieldFactoryfields";a:5:{i:0;O:27:"CronExpression_MinutesField":0:{}i:1;O:25:"CronExpression_HoursField":0:{}i:2;O:30:"CronExpression_DayOfMonthField":0:{}i:3;O:25:"CronExpression_MonthField":0:{}i:4;O:29:"CronExpression_DayOfWeekField":0:{}}}}}

**Comment by rezzz-dev** [comment] 2017-08-03 16:22
🤔

**Comment by crodas** [comment] 2017-08-03 16:22
The `GD_CCC_CronSchedule` class, which is not created by Subscriptions (as far as I remember), is not being found. I guess another plugin is using Action Scheduler as well and they are not loading their class until they need it. If I were you I would `grep` (`grep -Ri GD_CCC_CronSchedule ./wp-content/plugins`) to find where that class is defined and which plugin uses it and tell them they should load their class.

**Comment by rezzz-dev** [comment] 2017-08-03 16:28
Correct - that class is custom built (prior to me coming on board) what was happening was that the Scheduled Actions screen was bombing out and not displaying anything. So I disabled that plugin. When I re-enable that plugin and load the screen [this is what's displayed](https://cl.ly/1c0U1o390a3d) and there's no errors at all.

**Comment by rezzz-dev** [comment] 2017-08-03 16:36
```
/**
 * Class CCC_CronSchedule
 */
class GD_CCC_CronSchedule implements ActionScheduler_Schedule {
	/** @var DateTime */
	private $start = NULL;
	private $start_timestamp = 0;
	/** @var CronExpression */
	private $cron = NULL;

	public function __construct( DateTime $start, CronExpression $cron ) {
		$this->start = $start;
		$this->cron = $cron;

	}

	/**
	 * @param DateTime $after
	 * @return DateTime|null
	 */
	public function next( DateTime $after = NULL ) {
		$after = empty($after) ? clone $this->start : clone $after;
		return $this->cron->getNextRunDate($after, 0, false);
	}


	/**
	 * For PHP 5.2 compat, since DateTime objects can't be serialized
	 * @return array
	 */
	public function __sleep() {
		$this->start_timestamp = $this->start->format('U');
		return array(
			'start_timestamp',
			'cron'
		);
	}

	public function __wakeup() {
		$this->start = as_get_datetime_object($this->start_timestamp);
	}
}
```

Is the custom class that was built prior to me coming on board.

**Comment by jbrinley** [comment] 2017-08-03 17:09
Is this because of the update to the Cron Expression library (using the upstream version rather than the PHP 5.2-compatible back-port)?

**Comment by crodas** [comment] 2017-08-03 17:16
@rezzz-dev Can you load that class _before_ the admin is rendered? Perhaps right on the `plugins_loaded` action

**Comment by thenbrent** [comment] 2017-08-03 20:13
@jbrinley it's possible, but it shouldn't be caused by that. We haven't released that change in Subscriptions.

**Comment by rezzz-dev** [comment] 2017-08-03 20:21
I will give that a try @crodas and report back

**Comment by thenbrent** [comment] 2017-08-24 22:30
Closing this one. @rezzz-dev let us know if loading the class didn't fix the issue. But really, this relates to a custom `GD_CCC_CronSchedule` class, so I'm not sure we can provide much extra help.

**Closed by thenbrent** 2017-08-24 22:30 UTC
