### ISSUE TITLE
The QueueRunner can be bricked because failed actions sometimes aren't unclaimed

### ISSUE THREAD

**Issue by javorszky** [Prospress/action-scheduler#51] opened 2016-04-01 00:00 UTC
So far I have no idea why that happens, but occasionally there are failed actions, irrespective of the post store used, that still have their claim ids intact.

Because the Q runner checks how many distinct claim ids are in the store, and compares that to a predefined number, we can run into a situation where if there are 5 different failed actions from 5 different times with their claim ids still in, the Q runner will not start a new batch.

I think [this piece of code](https://github.com/Prospress/action-scheduler/blob/master/classes/ActionScheduler_QueueCleaner.php#L67-L70) is missing an `unclaim_action` call...

**Comment by thenbrent** [comment] 2016-05-06 23:41
Closing this as from memory, it was by design.

The idea was that if more than `'action_scheduler_queue_runner_concurrent_batches'` actions failed, we don't want to keep running queues of actions because we assume they'll probably just keep failing and causing more issues to cleanup. Instead, we want to halt the queue until the issue is resolved.

No one has ever been affected by this many failures in a real site yet fortunately.

**Closed by thenbrent** 2016-05-06 23:41 UTC
Labels: bug:needs-confirmation
