### ISSUE TITLE
wc_get_orders() sometimes behaves differently when run in a scheduled action

### ISSUE THREAD

**Issue by shaunek-hero** [Prospress/action-scheduler#936] opened 2023-04-07 18:54 UTC
I had a feature that involved hooking into `woocommerce_checkout_order_processed` event which worked solidly for several months, and then when I moved it to run in ActionScheduler it started to be flakey. Specifically the underlying SQL query has stopped being 100% predictable and as far as I can tell this only happens when run within an ActionScheduler task. I'm wondering if it could be some sort of bug in ActionSchedule that is causing this odd behavior, but I'm really unsure where the cause could be.

The code snippet under question includes a query that sometimes takes a couple seconds to run, which caused problems and is the reason I moved it to run asynchronously within ActionScheduler. The critical code looks approximately like this:

```php
$orders = wc_get_orders([
    'limit' => 1, 
    'exclude' => [$order_id_that_was_just_placed],
    'customer' => $user_email, // a legit email is being passed
    'payment_method' => $payment_method, // might be something like 'my_special_payment_method'
    'status' => ['wc-pending', 'wc-processing', 'wc-on-hold', 'wc-completed'],
    'return' => 'ids'
]);
```
The problem is sometimes the underlying SQL query that is run does not include the checks for the customer email and payment method. Many times the SQL query does though! I haven't figured out a pattern and I am adding all kinds of crazy logging statements all over to get to the bottom of it, but thought I would reach out and see if anybody else has reported a similar problem or if there is a common problem you know of that I can do to mitigate the problem.

I've added some extra logging to get some insights. Logging out `$wpdb->last_query` right after the query runs sometimes I get a query that formed properly. Here is what it SHOULD look like all the time:
```sql
SELECT   wp_posts.ID
FROM wp_posts  INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id )  INNER JOIN wp_postmeta AS mt1 ON ( wp_posts.ID = mt1.post_id )
WHERE 1=1  AND wp_posts.ID NOT IN (95079) AND (
  ( wp_postmeta.meta_key = '_payment_method' AND wp_postmeta.meta_value = 'my_special_payment_method' )
  AND
  (
    ( mt1.meta_key = '_billing_email' AND mt1.meta_value IN ('some.email@yahoo.com') )
  )
) AND wp_posts.post_type IN ('shop_order', 'shop_order_refund') AND ((wp_posts.post_status = 'wc-pending' OR wp_posts.post_status = 'wc-processing' OR wp_posts.post_status = 'wc-on-hold' OR wp_posts.post_status = 'wc-completed'))
GROUP BY wp_posts.ID
ORDER BY wp_posts.menu_order, wp_posts.post_date DESC
LIMIT 0, 5
```
However, more than half the time the output query looks like this (notice the missing payment method and billing email in join/where):
```sql
SELECT   wp_posts.ID
FROM wp_posts
WHERE 1=1  AND wp_posts.ID NOT IN (95010) AND wp_posts.post_type IN ('shop_order', 'shop_order_refund') AND ((wp_posts.post_status = 'wc-pending' OR wp_posts.post_status = 'wc-processing' OR wp_posts.post_status = 'wc-on-hold' OR wp_posts.post_status = 'wc-completed'))

ORDER BY wp_posts.menu_order, wp_posts.post_date DESC
LIMIT 0, 5
```
I'm adding logging all over the place now, and just to illustrated how odd this is, within WC_Order_Data_Store_CPT->query() I added some special logging that would print out the "$args" that it builds up just to make sure that the payment method and email are, indeed getting built into the "meta_query" and indeed it is. Here is the log output (this log output corresponds to the previous query above that DID NOT include payment/customer email in query):
```
2023-04-07T12:04:03+00:00 INFO The order query args include customer emails: Array
(
    [errors] => Array
        (
        )

    [meta_query] => Array
        (
            [0] => Array
                (
                    [key] => _payment_method
                    [value] => my_special_payment_method
                    [compare] => =
                )

            [1] => Array
                (
                    [customer_emails] => Array
                        (
                            [key] => _billing_email
                            [value] => Array
                                (
                                    [0] => legit.email@gmail.com
                                )

                            [compare] => IN
                        )

                )

        )

    [post__not_in] => Array
        (
            [0] => 95010
        )

    [posts_per_page] => 5
    [paginate] =>
    [order] => DESC
    [orderby] => date
    [fields] => ids
    [post_type] => Array
        (
            [0] => shop_order
            [1] => shop_order_refund
        )

    [customer] => legit.email@gmail.com
    [post_status] => Array
        (
            [0] => wc-pending
            [1] => wc-processing
            [2] => wc-on-hold
            [3] => wc-completed
        )

    [paged] => 1
    [date_query] => Array
        (
        )

    [no_found_rows] => 1
)
```

Again, the underlying query has been consistent when I run this code from the`woocommerce_checkout_order_processed` hook, it only seems to be flakey when run within ActionScheduler.

Any help or insights are greatly appreciated.

**Comment by vedanshujain** [comment] 2023-04-11 14:26
This is pretty odd behavior, as far as I know, AS does not change anything for the wc_get_orders behavior. Can you share the surrounding code of this action? FWIW I can reproduce the buggy query exactly when the variables `user_email` `payment_method` are not set, maybe in some cases they are null? 

In any case we would need more info to reproduce and figure out if there is indeed a bug.

**Comment by barryhughes** [comment] 2023-05-09 00:16
Since there has been no further feedback, we'll close this issue. Feel free to create a new one if you need further help (and if so, please provide the additional information requested). Thanks!

**Closed as completed by barryhughes** 2023-05-09 00:16 UTC
Labels: needs feedback
