### ISSUE TITLE
as_unschedule_all_actions not working

### ISSUE THREAD

**Issue by cseevinck** [Prospress/action-scheduler#956] opened 2023-05-23 22:41 UTC
I have some code that runs on receipt of a WordPress rest Api post. This code creates a blog post and saves a list of image ids. When the post is complete make the following call to start a recurring process: 
$resp = as_schedule_recurring_action( time(), 2, 'tsbs-async-execute-hook', array( 'tsbs' => null ), 'tsbs-thumbnails' );

The code that runs each time the event fires, will build the thumbnails for one image (using the id list above) and then quit. When the image list is exhausted I do the below call to stop the recurring event. 
as_unschedule_action( 'tsbs-async-execute-hook', array( 'tsbs' => null ), 'tsbs-thumbnails' ); 

The setup is a plugin on one wordpress site that sends post data (lots of ACF Images) via rest api to another wordpress site. The receiving site does what is described above. The post data is sent when a user on the sending side does a post save. When the post has been copied the recurring process is no longer needed.

**Comment by barryhughes** [comment] 2023-05-24 20:48
Hi @cseevinck,

If I create a recurring action via WP CLI it seems to work as expected:

```sh
wp eval "as_schedule_recurring_action( time(), 2, 'do_async_work', ['foo' => 'bar'], 'group' );"
```

So long as I have added a callback for my action, it successfully executes and is re-scheduled as expected. Unscheduling also appears to work. Again via WP CLI:

```sh
wp eval "as_unschedule_action( 'do_async_work', ['foo' => 'bar'], 'group' );"
```

This removes `do_async_work` from the list of pending actions. However, I can think of a couple of possibilities as to why things might not be working in your case:

- A new recurring action is being created immediately or very soon after the previous action was unscheduled.
- Or, there could a race condition (in which the action is executed and rescheduled at approximately the same time it is unscheduled by a different process ... though if this were the cause, I'd expect it to happen only rarely).

Some questions/ideas to help get to the bottom of this:

- Can you add logging, complete with timestamps, to your schedule and unschedule calls, so we can look at the sequence of events?
- Can you test a scenario where the site initiating the REST API requests is prevented from doing so (ie, there is no risk of new requests triggering re-scheduling)? Does unscheduling work now?

**Comment by cseevinck** [comment] 2023-05-26 23:07
Barry,
Thanks so much for your response.
I checked the items you mentioned and still cannot see what i'm doing
wrong. I stripped my plugin down to just basics and am attaching it to this
email. The way to do my test is to install and activate the plugin and to
go to Tools->Test Action Sched and hit "Save Changes". That will execute my
test code. I have a bunch of logging statements in there.
Thanks again for your help.

Corky Seevinck

***@***.***

801 694 6623 <8016946623>

chs-webs.com

**Comment by barryhughes** [comment] 2023-05-27 04:47
Hi Corky, 

Unfortunately, the attachment did not come through: you may need to login to GitHub and reply here directly (it's possible to drag and drop files, including zip files, into your reply) rather than replying by email—or else provide a download link, or perhaps create a [Gist](https://gist.github.com/).

Thanks!

**Comment by cseevinck** [comment] 2023-05-27 17:33
Thanks Barry,
Here is the file.
[test-action-sched.zip](https://github.com/woocommerce/action-scheduler/files/11582642/test-action-sched.zip)
Cheers

**Comment by barryhughes** [comment] 2023-05-29 16:49
So it seems like the unscheduling and re-scheduling happens in the same function, and it doesn't return early:

```php
function run_the_test() {
	// clear thumbnail_array.
	$options                    = get_option( 'tas_settings' );
	$options['thumbnail_array'] = serialize( array() );
	update_option( 'tas_settings', $options );

	chs_log( 'at start: kill the scheduling processes to make sure' );
	as_unschedule_action( 'tas-async-execute-hook', array( 'tas' => 'tas' ), 'tas-thumbnails' );
	// build the array
	$options = get_option( 'tas_settings' );
	$arr     = array( 11111, 22222, 33333, 44444 );
	foreach ( $arr as $value ) {
		$image_id = $value;
		tas_put_image_id( $image_id );
	}

	$options  = get_option( 'tas_settings' );
	$imgs_str = $options['thumbnail_array'];
	$imgs_arr = unserialize( $imgs_str );
	chs_log( $imgs_arr, 'run_the_test - $imgs_arr after all puts ' );

	chs_log( 'Schedule the event: as_schedule_recurring_action( time(), 2, "tas-async-execute-hook", array( "tas" => null ), "tas-thumbnails" )' );
	$resp = as_schedule_recurring_action( time(), 2, 'tas-async-execute-hook', array( 'tas' => 'tas' ), 'tas-thumbnails' );
	chs_log( $resp, 'tas_schedule_thumbnail_rebuilds: Response from Schedule event' );
}
```

Abbreviating the code to:

```php
function run_the_test() {
	as_unschedule_action( 'tas-async-execute-hook', array( 'tas' => 'tas' ), 'tas-thumbnails' );
	$resp = as_schedule_recurring_action( time(), 2, 'tas-async-execute-hook', array( 'tas' => 'tas' ), 'tas-thumbnails' );
}
```

You can see how this will lead to `tas-async-execute-hook` being 'ever-present'. With that in mind I do not think there is a bug here, it's more a matter of how you structure your code (which we can't really help with), so I'll go ahead and close this.

**Closed as completed by barryhughes** 2023-05-29 16:49 UTC
Labels: type: support request
