### ISSUE TITLE
Keep getting "Scheduled action for hook_name will not be executed as no callbacks are registered'

### ISSUE THREAD

**Issue by stasou** [Prospress/action-scheduler#886] opened 2022-11-14 17:33 UTC
Hi, as stated in the title, I keep getting this message for a reason I cannot resolve. Any help will be deeply appreciated.

Message: `Scheduled action for hook_name will not be executed as no callbacks are registered`

```
$order = wc_get_order( $order_id );
add_action('so_api_scheduled_action', 'so_api_process_order', 10, 1);
$queue_id = as_enqueue_async_action( 'so_api_scheduled_action', array( $order ) );

[....]
function so_api_process_order( $order ) {
// does stuff
}
```

I don't know how to look at it, apparently, there is a callback attached to the hook. If I run the function `so_api_process_order` manually, it works as expected.

Tools in admin give me this log abstract:
```
    2022-11-14 17:32:35 +0000
    action created
    2022-11-14 17:32:50 +0000
    action started via WP CLI
    2022-11-14 17:32:50 +0000
    action failed via WP CLI: Scheduled action for so_api_scheduled_action will not be executed as no callbacks are registered.
```

**Comment by stasou** [comment] 2022-11-15 07:33
So, I found the way to go around this. But I believe it should be better documented.

My first approach, that didn't work, was to have the action added when the function was called.

```
function that_does_something() {
    // ...
    add_action('so_api_scheduled_action', 'so_api_process_order', 10, 1);
    as_enqueue_async_action( 'so_api_scheduled_action', array( $order ) );
   // ...
}
```
This didn't work, because there "was no registered callback for the action"

But moving the `add_action` to the top scope (directly in functions.php):
```
add_action('so_api_scheduled_action', 'so_api_process_order', 10, 1);
function that_does_something() {
    // ...
        as_enqueue_async_action( 'so_api_scheduled_action', array( $order ) );
   // ...
}
```
Seems to work

**Comment by jorgeatorres** [comment] 2022-11-29 17:59
Hi @stasou!

Thanks for reaching out. This is standard practice in WordPress execution execution model: you have to make sure the callback is registered earlier than when the action is performed (in this case, the queue runner runs).

You don't necessarily have to make the `add_action()` call "top level", but you do have to make sure it happens _before_ the scheduled action is run.

Keep in mind that `as_enqueue_async_action()` just schedules the action, but the runner runs it at a later point (and different request), so if `that_does_something()` is called _after_ the runner is executed, then you'd see the error you were seeing (for a previously scheduled action, not the one you're just scheduling).

For example, assuming your actions are running through the default AS WP-Cron runner, you'd have to make sure the callbacks are registered on a hook fired before WP-Cron runs.
A valid choice would be top scope, but that's not necessarily the only way to do it.

Given this is not a bug, I'm going to close this for now, but feel free to re-open if I've misinterpreted anything. We're definitely here to help.

**Closed as completed by jorgeatorres** 2022-11-29 17:59 UTC
