### ISSUE TITLE
Fatal error: Woocommerce

### ISSUE THREAD

**Issue by lakayanzz** [Prospress/action-scheduler#986] opened 2023-09-13 01:05 UTC
Hello, I have a problem, I have a WordPress and yesterday the website stopped working and this message started appearing through the Woocomerce plugins for no reason, it wouldn't let me enter the administrator and I deactivated all the plugins and I discovered that the one that fails is woocommerce when I activate it.

Fatal error: Uncaught RuntimeException: Error al guardar la acción: Error al guardar la acción: Unknown column 'priority' in 'field list' in /home/orbits/orbitsstore.cl/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 /home/orbits/orbitsstore.cl/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action() #1 /home/orbits/orbitsstore.cl/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(327): ActionScheduler_HybridStore->save_action() #2 /home/orbits/orbitsstore.cl/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(315): ActionScheduler_ActionFactory->store() #3 /home/orbits/orbitsstore.cl/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php(102): ActionScheduler_ActionFactory->create() #4 /home/orbits/orbitsstore.cl/wp-content/pl in /home/orbits/orbitsstore.cl/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44
Ha habido un error crítico en esta web. Por favor, comprueba la bandeja de entrada del correo electrónico del administrador de tu sitio para obtener instrucciones.

  I hope you can help me

**Comment by barryhughes** [comment] 2023-09-13 14:43
Thanks for the report. Closing as this is essentially a duplicate of/repeating information we have in https://github.com/woocommerce/action-scheduler/issues/973.

**Closed as completed by barryhughes** 2023-09-13 14:43 UTC
